use crate::objects::container::Container;
use crate::objects::object::Object;
use crate::objects::player::Player;

impl Default for Container {
    fn default() -> Self {
        Self {
            object: Object::default(),
            num_slots: None,
            slot: [None; 36],
        }
    }
}

impl Default for Player {
    fn default() -> Self {
        Player {
            unit: Default::default(),
            duel_arbiter: None,
            flags: None,
            guild_id: None,
            guild_rank: None,
            bytes: None,
            bytes_2: None,
            bytes_3: None,
            duel_team: None,
            guild_timestamp: None,
            player_quests: [None; 25],
            visible_items: [None; 19],
            chosen_title: None,
            fake_inebriation: None,
            unknown_af: None,
            field_inv_slot_head: [None; 23],
            field_pack_slot: [None; 16],
            field_bank_slot: [None; 28],
            field_bank_bag_slot: [None; 7],
            field_vendor_buyback_slot: [None; 12],
            field_keyring_slot: [None; 32],
            field_currency_token_slot: [None; 32],
            farsight: None,
            field_known_titles: [None; 3],
            field_known_currencies: None,
            xp: None,
            next_level_xp: None,
            skill_info: [None; 384],
            character_points: [None; 2],
            track_creatures: None,
            track_resources: None,
            block_percentage: None,
            dodge_percentage: None,
            parry_percentage: None,
            expertise: None,
            offhand_expertise: None,
            crit_percentage: None,
            ranged_crit_percentage: None,
            offhand_crit_percentage: None,
            spell_crit_percentage: [None; 7],
            shield_block: None,
            shield_block_crit_percentage: None,
            explored_zones: [None; 128],
            rest_state_experience: None,
            field_coinage: None,
            field_mod_damage_done_pos: [None; 7],
            field_mod_damage_done_neg: [None; 7],
            field_mod_damage_done_pct: [None; 7],
            field_mod_healing_done_pos: None,
            field_mod_healing_pct: None,
            field_mod_healing_done_pct: None,
            field_mod_target_resistance: None,
            field_mod_target_physical_resistance: None,
            field_bytes: None,
            ammo_id: None,
            self_res_spell: None,
            field_pvp_medals: None,
            field_buyback_price: [None; 12],
            field_buyback_timestamp: [None; 12],
            field_kills: None,
            field_today_contribution: None,
            field_yesterday_contribution: None,
            field_lifetime_honorable_kills: None,
            field_bytes2: None,
            watched_faction_index: None,
            combat_rating: [None; 25],
            field_arena_team_info: [None; 21],
            field_honor_currency: None,
            field_arena_currency: None,
            field_max_level: None,
            field_daily_quests: [None; 25],
            rune_regen: None,
            no_reagent_cost: [None; 3],
            glyph_slots: [None; 6],
            glyphs: [None; 6],
            glyphs_enabled: None,
            pet_spell_power: None,
        }
    }
}
