[workspace]
members = [
    "./rustycraft_auth_server",
    "./rustycraft_common",
    "./rustycraft_database",
    "./rustycraft_logging",
    "./rustycraft_world_server",
    "./rustycraft_world_packets",
    "./rustycraft_derive",
]