[workspace]
members = [
    "./ashcraft_auth_server",
    "./ashcraft_common",
    "./ashcraft_database",
    "./ashcraft_logging",
    "./ashcraft_world_server",
    "./ashcraft_world_packets",
    "./ashcraft_derive",
]