[package]
name = "rustycraft_world_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustycraft_logging = { path = "../rustycraft_logging" }
rustycraft_protocol = { path = "../rustycraft_protocol" }

rand = "0.8"
deku = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
aes-gcm = "0.9"
hmac = "0.12"
sha2 = "0.10"
tokio = { version = "1.17", features = ["full"] }
anyhow = "1.0"
bytes = "1.1"
async-trait = "0.1"
log = "0.4"
