[package]
name = "rustycraft_world_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustycraft_logging = { path = "../rustycraft_logging" }
rustycraft_proc_macro = { path = "../rustycraft_proc_macro" }

tokio = { version = "1.17", features = ["full"] }
anyhow = "1.0"
bytes = "1.1"
async-trait = "0.1"
log = "0.4"
