[package]
name = "rustycraft_world_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustycraft_logging = { path = "../rustycraft_logging" }
rustycraft_protocol = { path = "../rustycraft_protocol" }
rustycraft_database = { path = "../rustycraft_database" }
rustycraft_common = { path = "../rustycraft_common" }

rand = "0.8"
deku = "0.13"
aes-gcm = "0.9"
hmac = "0.12"
sha2 = "0.10"
boring-sys = "2.0"
boring = "2.0"
lazy_static = "1.4"
tokio = { version = "1.17" }
anyhow = "1.0"
bytes = "1.1"
async-trait = "0.1"
log = "0.4"
chrono = "0.4"
chrono-tz = "0.6"
enum-iterator = "0.7"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
